# Generated by Django 3.2.16 on 2023-01-25 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='サークル名')),
                ('num', models.IntegerField(verbose_name='部員数')),
                ('money', models.IntegerField(verbose_name='部費')),
                ('place', models.CharField(max_length=50, verbose_name='活動場所')),
                ('time', models.CharField(max_length=50, verbose_name='活動時間')),
                ('image', models.ImageField(upload_to='images/')),
                ('mail', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('twitter', models.SlugField(blank=True, null=True, verbose_name='twitter')),
                ('insta', models.SlugField(blank=True, null=True, verbose_name='instagram')),
                ('category', models.CharField(choices=[('運動系', '運動系'), ('文化系', '文化系'), ('同好会', '同好会')], max_length=3, verbose_name='カテゴリ')),
                ('text', models.TextField(verbose_name='一言')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('編集者名', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
